Repository bciobanu/pain, pull requests merged in 2020-06, with the labels that each got.

#9 [Client] Filter detected rectangles
  app/Pain/Pain.xcodeproj/project.xcworkspace/xcuserdata/andrei.xcuserdatad/UserInterfaceState.xcuserstate
  app/Pain/Pain/Interface/Camera/RectangleDetectionViewController.swift
Labels: enhancement

#10 [Client] Api calls
  .gitignore
  app/Pain/Pain.xcodeproj/project.pbxproj
  app/Pain/Pain.xcodeproj/project.xcworkspace/xcuserdata/florin.xcuserdatad/UserInterfaceState.xcuserstate
  app/Pain/Pain.xcodeproj/xcuserdata/florin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  app/Pain/Pain/Assets.xcassets/CameraIcon.imageset/Contents.json
  app/Pain/Pain/Assets.xcassets/CameraIcon.imageset/icons8-camera-96.png
  app/Pain/Pain/Assets.xcassets/camera_icon.jpg
  app/Pain/Pain/Base.lproj/Main.storyboard
  app/Pain/Pain/Info.plist
  app/Pain/Pain/Interface/PaintingDisplay/PaintingTableViewController.swift
  app/Pain/Pain/Interface/PaintingDisplay/PaintingViewController.swift
  app/Pain/Pain/Model/Painting.swift
  app/Pain/Pain/NetworkManager.swift
  app/Pain/Pain/Pain.entitlements
Labels: implementation

#11 [Client] Made the request async + call api with the detection
  app/Pain/Pain/Base.lproj/Main.storyboard
  app/Pain/Pain/Interface/Camera/RectangleDetectionViewController.swift
  app/Pain/Pain/Interface/PaintingDisplay/PaintingTableViewController.swift
  app/Pain/Pain/Interface/PaintingDisplay/PaintingViewController.swift
  app/Pain/Pain/NetworkManager.swift
Labels: implementation

#12 [Client] Fix image orientation when cutting
  app/Pain/Pain/Interface/Camera/RectangleDetectionViewController.swift
Labels: bug

#13 [Client] Text to speech
  app/Pain/Pain.xcodeproj/project.xcworkspace/xcuserdata/florin.xcuserdatad/UserInterfaceState.xcuserstate
  app/Pain/Pain.xcodeproj/xcuserdata/florin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  app/Pain/Pain/Assets.xcassets/TextToSpeech.imageset/Contents.json
  app/Pain/Pain/Assets.xcassets/TextToSpeech.imageset/icons8-speech-96.png
  app/Pain/Pain/Base.lproj/Main.storyboard
  app/Pain/Pain/Interface/PaintingDisplay/PaintingViewController.swift
Labels: implementation

#16 [Client] Better interface
  app/Pain/Pain.xcodeproj/project.pbxproj
  app/Pain/Pain.xcodeproj/project.xcworkspace/xcuserdata/andrei.xcuserdatad/UserInterfaceState.xcuserstate
  app/Pain/Pain/Base.lproj/Main.storyboard
  app/Pain/Pain/Interface/Camera/CameraViewController.swift
  app/Pain/Pain/Interface/Camera/RectangleDetectionViewController.swift
  app/Pain/Pain/Interface/PaintingDisplay/PaintingTableViewController.swift
  app/Pain/Pain/Interface/PaintingDisplay/PaintingViewController.swift
  app/Pain/Pain/NetworkManager.swift
Labels: bug, enhancement

#17 [Client] Fix orientation issues
  app/Pain/Pain.xcodeproj/project.xcworkspace/xcuserdata/andrei.xcuserdatad/UserInterfaceState.xcuserstate
  app/Pain/Pain/Base.lproj/Main.storyboard
  app/Pain/Pain/Info.plist
  app/Pain/Pain/Interface/Camera/CameraViewController.swift
  app/Pain/Pain/Interface/Camera/RectangleDetectionViewController.swift
Labels: bug

#22 [Client] Add a loading indicator
  app/Pain/Pain/Interface/Camera/RectangleDetectionViewController.swift
  app/Pain/Pain/Interface/PaintingDisplay/PaintingTableViewController.swift
  app/Pain/Pain/Interface/PaintingDisplay/PaintingViewController.swift
Labels: enhancement
